# Generated by Django 5.0.4 on 2025-03-20 07:29

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.gis.db import models as gis_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('farm_street', models.CharField(max_length=100)),
                ('farm_state', models.CharField(max_length=20)),
                ('farm_postcode', models.CharField(max_length=6)),
                ('farm_bio', models.TextField()),
                ('farm_image', models.ImageField(blank=True, default='images/farm_images/default_image.png', null=True, upload_to='images/farm_images')),
                ('farm_coordinates', gis_models.PolygonField(srid=4326, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileCategoryName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
                ('reviewDate', models.DateField(null=True)),
                ('file', models.FileField(upload_to='files/')),
                ('fileCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FarmAcc.filecategory')),
            ],
        ),
        migrations.CreateModel(
            name='LinkingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linking_codes', to='FarmAcc.farminfo')),
            ],
        ),
    ]
