# Generated by Django 5.1.7 on 2025-03-24 08:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FarmAcc', '0002_remove_farminfo_farm_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDVIRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('image', models.ImageField(upload_to='ndvi_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmAcc.farminfo')),
            ],
        ),
    ]
