# Generated by Django 5.0.4 on 2025-04-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_ndvireport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndvireport',
            name='file_path',
            field=models.FileField(upload_to='report/'),
        ),
    ]
