# Generated by Django 5.0.4 on 2025-05-04 10:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmAcc', '0002_remove_farminfo_farm_coordinates'),
        ('Map', '0003_alter_ndvireport_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_path', models.FileField(upload_to='report/')),
                ('geolocation', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FarmAcc.farminfo')),
            ],
        ),
    ]
